{"timestamp":"2025-08-04T08:26:40.734388","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-08-04T08:26:40.735182","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/toll_data_etl_bash.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-08-04T08:26:40.773996Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-04T08:26:40.774345Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-04T08:26:40.774587Z","level":"info","event":"Current task name:unzip_data","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-04T08:26:40.774818Z","level":"info","event":"Dag name:ETL_toll_data","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-04T08:26:40.773301","level":"info","event":"Tmp dir root location: /tmp","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-08-04T08:26:40.774879","level":"info","event":"Running command: ['/usr/bin/bash', '-c', '\\n    echo \"üîÑ Unzipping tolldata archive...\"\\n\\n    if tar -xzf /tmp/data/tolldata.tgz -C /tmp/data; then\\n        echo \"‚úÖ tolldata.tgz extracted successfully.\"\\n    else\\n        echo \"‚ùå Failed to extract tolldata.tgz\" >&2\\n        exit 1\\n    fi\\n    ']","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-08-04T08:26:40.789988","level":"info","event":"Output:","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-08-04T08:26:40.792544","level":"info","event":"üîÑ Unzipping tolldata archive...","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-08-04T08:26:40.795939","level":"info","event":"tar (child): /tmp/data/tolldata.tgz: Cannot open: No such file or directory","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-08-04T08:26:40.796075","level":"info","event":"tar (child): Error is not recoverable: exiting now","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-08-04T08:26:40.796367","level":"info","event":"tar: Child returned status 2","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-08-04T08:26:40.796829","level":"info","event":"tar: Error is not recoverable: exiting now","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-08-04T08:26:40.796960","level":"info","event":"‚ùå Failed to extract tolldata.tgz","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-08-04T08:26:40.797151","level":"info","event":"Command exited with return code 1","logger":"airflow.task.hooks.airflow.providers.standard.hooks.subprocess.SubprocessHook"}
{"timestamp":"2025-08-04T08:26:40.797815","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"AirflowException","exc_value":"Bash command failed. The command returned a non-zero exit code 1.","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":877,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1164,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/bash.py","lineno":232,"name":"execute"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-08-04T08:26:40.825761Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-04T08:26:40.826378Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-04T08:26:40.826592Z","level":"info","event":"Task:<Task(BashOperator): unzip_data>","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-04T08:26:40.826875Z","level":"info","event":"Failure caused by Bash command failed. The command returned a non-zero exit code 1.","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-04T08:26:40.830315","level":"error","event":"Top level error","logger":"task","error_detail":[{"exc_type":"UndefinedError","exc_value":"'airflow.sdk.execution_time.task_runner.RuntimeTaskInstance object' has no attribute 'mark_success_url'","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1302,"name":"main"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1269,"name":"finalize"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1110,"name":"_send_task_error_email"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py","lineno":411,"name":"_get_email_subject_content"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py","lineno":408,"name":"render"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py","lineno":244,"name":"render_template_to_string"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py","lineno":239,"name":"render_template"},{"filename":"<template>","lineno":26,"name":"root"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/jinja2/runtime.py","lineno":859,"name":"_fail_with_undefined_error"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-08-04T08:26:40.847093Z","level":"warning","event":"Process exited abnormally","exit_code":1,"logger":"task"}
